from .dispatcher import register_dispatcher
from .start_handler import start_handler
from .current_music_inline_query import current_music_inline_query
from .unlink_spotify_handler import unlink_spotify_handler
from .add_friend_handler import add_friend_handler
from .all_messages_handler import all_messages_handler

