"""spotify friends

Revision ID: 8e1b03f6f028
Revises: 3d95b39824af
Create Date: 2021-06-27 23:58:37.356591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1b03f6f028'
down_revision = '3d95b39824af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('friend_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['friend_uuid'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_friends_friend_uuid'), 'friends', ['friend_uuid'], unique=False)
    op.create_index(op.f('ix_friends_user_uuid'), 'friends', ['user_uuid'], unique=False)
    op.add_column('users', sa.Column('spotify_user_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spotify_user_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spotify_user_pic')
    op.drop_column('users', 'spotify_user_name')
    op.drop_index(op.f('ix_friends_user_uuid'), table_name='friends')
    op.drop_index(op.f('ix_friends_friend_uuid'), table_name='friends')
    op.drop_table('friends')
    # ### end Alembic commands ###
